//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sc.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Account_Settings {
            get {
                return ResourceManager.GetString("Account Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is limited, idling process is unavailable until the restriction is removed!.
        /// </summary>
        public static string BotAccountLimited {
            get {
                return ResourceManager.GetString("BotAccountLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is locked, idling process is permanently unavailable!.
        /// </summary>
        public static string BotAccountLocked {
            get {
                return ResourceManager.GetString("BotAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to Steam!.
        /// </summary>
        public static string BotConnected {
            get {
                return ResourceManager.GetString("BotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string BotConnecting {
            get {
                return ResourceManager.GetString("BotConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Steam Network lost. Reconnecting....
        /// </summary>
        public static string BotConnectionLost {
            get {
                return ResourceManager.GetString("BotConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from Steam!.
        /// </summary>
        public static string BotDisconnected {
            get {
                return ResourceManager.GetString("BotDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting....
        /// </summary>
        public static string BotDisconnecting {
            get {
                return ResourceManager.GetString("BotDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to disconnect the client. Abandoning this bot instance!.
        /// </summary>
        public static string BotHeartBeatFailed {
            get {
                return ResourceManager.GetString("BotHeartBeatFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not starting this bot instance because it&apos;s disabled in config file!.
        /// </summary>
        public static string BotInstanceNotStartingBecauseDisabled {
            get {
                return ResourceManager.GetString("BotInstanceNotStartingBecauseDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged off of Steam: {0}.
        /// </summary>
        public static string BotLoggedOff {
            get {
                return ResourceManager.GetString("BotLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged on as {0}..
        /// </summary>
        public static string BotLoggedOn {
            get {
                return ResourceManager.GetString("BotLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string BotLoggingIn {
            get {
                return ResourceManager.GetString("BotLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account seems to be used in another ASF instance, which is undefined behaviour, refusing to keep it running!.
        /// </summary>
        public static string BotLogonSessionReplaced {
            get {
                return ResourceManager.GetString("BotLogonSessionReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limit exceeded, we will retry after {0} of cooldown....
        /// </summary>
        public static string BotRateLimitExceeded {
            get {
                return ResourceManager.GetString("BotRateLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnecting....
        /// </summary>
        public static string BotReconnecting {
            get {
                return ResourceManager.GetString("BotReconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed expired login key!.
        /// </summary>
        public static string BotRemovedExpiredLoginKey {
            get {
                return ResourceManager.GetString("BotRemovedExpiredLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping....
        /// </summary>
        public static string BotStopping {
            get {
                return ResourceManager.GetString("BotStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login to Steam: {0}/{1}.
        /// </summary>
        public static string BotUnableToLogin {
            get {
                return ResourceManager.GetString("BotUnableToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string CameraLabel {
            get {
                return ResourceManager.GetString("CameraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string CommunityLabel {
            get {
                return ResourceManager.GetString("CommunityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionTimeout.
        /// </summary>
        public static string ConnectionTimeout {
            get {
                return ResourceManager.GetString("ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:
        ///{0}.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bot config is invalid. Please verify content of {0} and try again!.
        /// </summary>
        public static string ErrorBotConfigInvalid {
            get {
                return ResourceManager.GetString("ErrorBotConfigInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured {0} property is invalid: {1}.
        /// </summary>
        public static string ErrorConfigPropertyInvalid {
            get {
                return ResourceManager.GetString("ErrorConfigPropertyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistent database could not be loaded, if issue persists, please remove {0} in order to recreate the database!.
        /// </summary>
        public static string ErrorDatabaseInvalid {
            get {
                return ResourceManager.GetString("ErrorDatabaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failing: {0}.
        /// </summary>
        public static string ErrorFailingRequest {
            get {
                return ResourceManager.GetString("ErrorFailingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty!.
        /// </summary>
        public static string ErrorIsEmpty {
            get {
                return ResourceManager.GetString("ErrorIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null!.
        /// </summary>
        public static string ErrorObjectIsNull {
            get {
                return ResourceManager.GetString("ErrorObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request failed after {0} attempts!.
        /// </summary>
        public static string ErrorRequestFailedTooManyTimes {
            get {
                return ResourceManager.GetString("ErrorRequestFailedTooManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was created..
        /// </summary>
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was loaded..
        /// </summary>
        public static string FileLoaded {
            get {
                return ResourceManager.GetString("FileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string FriendsLabel {
            get {
                return ResourceManager.GetString("FriendsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Setting.
        /// </summary>
        public static string Global_Setting {
            get {
                return ResourceManager.GetString("Global Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isDebug .
        /// </summary>
        public static string isDebugLabel {
            get {
                return ResourceManager.GetString("isDebugLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in to {0}....
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginLimitDelay.
        /// </summary>
        public static string LoginLimitDelay {
            get {
                return ResourceManager.GetString("LoginLimitDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOutLabel {
            get {
                return ResourceManager.GetString("LogOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageLabel {
            get {
                return ResourceManager.GetString("MessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfileLabel {
            get {
                return ResourceManager.GetString("MyProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlineStatus.
        /// </summary>
        public static string OnlineStatus {
            get {
                return ResourceManager.GetString("OnlineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Photo.
        /// </summary>
        public static string PickPhotoLabel {
            get {
                return ResourceManager.GetString("PickPhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing our session!.
        /// </summary>
        public static string RefreshingOurSession {
            get {
                return ResourceManager.GetString("RefreshingOurSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteamProtocol.
        /// </summary>
        public static string SteamProtocol {
            get {
                return ResourceManager.GetString("SteamProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string StoreLabel {
            get {
                return ResourceManager.GetString("StoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        public static string TakePhotoLabel {
            get {
                return ResourceManager.GetString("TakePhotoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocking parental account....
        /// </summary>
        public static string UnlockingParentalAccount {
            get {
                return ResourceManager.GetString("UnlockingParentalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        public static string UploadAvatarLabel {
            get {
                return ResourceManager.GetString("UploadAvatarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your mobile authenticator device ID (including &quot;android:&quot;): .
        /// </summary>
        public static string UserInputDeviceID {
            get {
                return ResourceManager.GetString("UserInputDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your 2FA code from your Steam authenticator app: .
        /// </summary>
        public static string UserInputSteam2FA {
            get {
                return ResourceManager.GetString("UserInputSteam2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter SteamGuard auth code that was sent on your e-mail: .
        /// </summary>
        public static string UserInputSteamGuard {
            get {
                return ResourceManager.GetString("UserInputSteamGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Steam login: .
        /// </summary>
        public static string UserInputSteamLogin {
            get {
                return ResourceManager.GetString("UserInputSteamLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Steam parental code: .
        /// </summary>
        public static string UserInputSteamParentalCode {
            get {
                return ResourceManager.GetString("UserInputSteamParentalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Steam password: .
        /// </summary>
        public static string UserInputSteamPassword {
            get {
                return ResourceManager.GetString("UserInputSteamPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed!.
        /// </summary>
        public static string WarningFailed {
            get {
                return ResourceManager.GetString("WarningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed due to error: {0}.
        /// </summary>
        public static string WarningFailedWithError {
            get {
                return ResourceManager.GetString("WarningFailedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown value for {0}, please report this: {1}.
        /// </summary>
        public static string WarningUnknownValuePleaseReport {
            get {
                return ResourceManager.GetString("WarningUnknownValuePleaseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workaround for {0} bug has been triggered..
        /// </summary>
        public static string WarningWorkaroundTriggered {
            get {
                return ResourceManager.GetString("WarningWorkaroundTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebLimiterDelay.
        /// </summary>
        public static string WebLimiterDelay {
            get {
                return ResourceManager.GetString("WebLimiterDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like it&apos;s your first launch of the program, welcome!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
